### ISSUE TITLE
[openapi-generator] Boolean query parameter initialized as None

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-api-server#133]
Although the spec has the query parameter as boolean type:
```
   parameters:
     - in: query
       name: report_to_stdout
       description: Flag to indicate whether the pipeline shall print via
         via stdout the reports produced by the tools (required by QAA module)
       required: false
       schema:
         type: boolean
         default: false
```

the openapi-generator initializes the flag as `None`:
```
async def add_pipeline(request: web.Request, body, report_to_stdout=None) -> web.Response:
```
