### ISSUE TITLE
A list of commands is wrongly rendered within the config.yml

### ISSUE THREAD

**Issue by orviz** [EOSC-synergy/sqaaas-api-server#138]
E.g (note the 2 `--` minus in the list)
```
sqa_criteria:
  QC.Doc:
    repos:
      this_repo:
        commands:
        - - npm install
          - npm preview-docs
        container: qc.doc_randy-cream-rhinoceros
```
